{% set name = "micromagnetictests" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 988cacc0b43bcd31e8644e22cb0a72ea0b58e7be380e89aee0e75af2ea8d84ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scipy >=1.5
    - micromagneticmodel ==0.8.22

test:
  imports:
    - micromagnetictests
  commands:
    - python -c "import sys; import micromagnetictests; sys.exit(micromagnetictests.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Testing package for computational magnetism tools.
  doc_url: http://micromagnetictests.readthedocs.io
  dev_url: https://github.com/ubermag/micromagnetictests

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
