{% set name = "micromagnetictests" %}
{% set version = "0.63.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1d71fe86ee76aaa8432548868dc7b7ca1021cb4c2e66b458102ffb733181e06

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scipy >=1.5
    - micromagneticmodel >=0.63.0

test:
  imports:
    - micromagnetictests
  commands:
    - python -c "import sys; import micromagnetictests; sys.exit(micromagnetictests.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Testing package for computational magnetism tools.
  doc_url: https://ubermag.github.io/documentation/micromagnetictests.html
  dev_url: https://github.com/ubermag/micromagnetictests

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
