{% set name = "micromagnetictests" %}
{% set version = "0.1.4" %}
{% set sha256 = "4b8959d41f88db67060730a3813b5d5e8c8b95aaeeba4b2f2e94a23e5f699adf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - micromagneticmodel ==0.8.19
    - scipy >=1.4

test:
  imports:
    - micromagnetictests
  commands:
    - python -c "import sys; import micromagnetictests as mt; sys.exit(mt.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Micromagnetic tests for Ubermag calculators.
  doc_url: http://micromagnetictests.readthedocs.io
  dev_url: https://github.com/ubermag/micromagnetictests

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
