{% set name = "micromagnetictests" %}
{% set version = "0.61.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cd817becd55ef73a8965963b849138d4ab63fddd3d5cac58a998e3c4d1d19c9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scipy >=1.5
    - micromagneticmodel >=0.61.0,<0.62.0

test:
  imports:
    - micromagnetictests
  commands:
    - python -c "import sys; import micromagnetictests; sys.exit(micromagnetictests.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Testing package for computational magnetism tools.
  doc_url: https://ubermag.github.io/documentation/micromagnetictests.html
  dev_url: https://github.com/ubermag/micromagnetictests

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
