{% set name = "micromagnetictests" %}
{% set version = "0.64.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 80d67607607dc606b4c904dec9eb7a78bcc2c598b4d90415505d68cdf8045982

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - scipy >=1.5
    - micromagneticmodel >=0.65.0
    - micromagneticdata >=0.66.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - micromagnetictests
  commands:
    - python -c "import sys; import micromagnetictests; sys.exit(micromagnetictests.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Testing package for computational magnetism tools.
  doc_url: https://ubermag.github.io/documentation/micromagnetictests.html
  dev_url: https://github.com/ubermag/micromagnetictests

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
