{% set name = "micromagnetictests" %}
{% set version = "0.61.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: acd81606058d81082e3e97d850d1cc5c5fdd43f72a44a3d3ded04c95ddc93f31

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - scipy >=1.5
    - micromagneticmodel >=0.61.0,<0.62.0

test:
  imports:
    - micromagnetictests
  commands:
    - python -c "import sys; import micromagnetictests; sys.exit(micromagnetictests.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Testing package for computational magnetism tools.
  doc_url: https://ubermag.github.io/documentation/micromagnetictests.html
  dev_url: https://github.com/ubermag/micromagnetictests

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
